config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions
  resource :session, only: %i[new create destroy]
  resources :pupils, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pupil.rb
class Pupil < ApplicationRecord
  has_secure_password
  validates :emails, presence: true, uniqueness: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  private

  def current_user
    @current_user ||= Pupil.find_by(id: session[:user_id]) if session[:user_id]


  end
end

app/controllers/pupils_controller.rb
class PupilsController < ApplicationController
  def new
    session[:current_time] = Time.now
    @pupil = Pupil.new
  end

  def create
    pupil_params = params.require(:pupil).permit(:names, :nicknames, :emails, :password)

    @pupil = Pupil.new(pupil_params)
    if @pupil.save
      redirect_to root_path, notice: 'You are registered'
    else
      flash.now[:alert] = "You have registered incorrectly"

      render :new
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[update show destroy edit]
  def create
    question = Question.create(question_params)


    redirect_to question_path(question), notice: "New question create!"
  end
  def update
    @question.update(question_params)
    redirect_to question_path(@question)
  end
  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def show
  end
  def index
    @question = Question.new
    @questions = Question.all
  end
  def new
    @question = Question.new
  end
  def edit
  end

  private

  def question_params
    params.require(:question).permit(:body, :user_id)
  end
  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    pupil_params = params.require(:session)

    pupil = Pupil.find_by(emails: pupil_params[:emails])&.authenticate(pupil_params[:password])

    if pupil.present?
      session[:user_id] = pupil.id

      redirect_to root_path, notice: 'You entered to site'
    else
      flash.now[:alert] = 'Wrong email or password'

      render :new
    end
  end
  def destroy
    session.delete(user_id)

    redirect_to root_path, notice: "You logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar">
        <p class = 'title-sm text-bold '><%= link_to "Ask Me", root_path %></p>
        <div>
          <% if current_user.present?%>
            <%= "@#{current_user.nicknames}" %>
            <%= button_to 'Log out', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Register', new_pupil_path, class: 'button button-yellow mr-sm'%>
            <%= link_to 'Sign in', new_session_path, class: 'button button-yellow'%>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message-alert"><%= flash[:alert] %> </p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pupils/new.html.erb
<div class = 'container'>
  <h2 class = 'title'> Join and ask!</h2>


  <div class = 'mt'>
    <%= form_with model: @pupil, data: {turbo: false}  do |form| %>
      <p><%= form.label :names, 'Your name'  %></p>
      <p><%= form.text_field :names, class: 'form-text-field' %></p>

      <p class = 'mt'><%= form.label :nicknames, "Your nick"  %></p>
      <p><%= form.text_field :nicknames, class: 'form-text-field' %></p>

      <p class = 'mt'><%= form.label :emails  %></p>
      <p><%= form.text_field :emails, class: 'form-text-field' %></p>

      <p class = 'mt'><%= form.label :password  %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>


      <p class = 'mt-lg'><%= form.submit 'Sign up', class: 'button button-main'  %></p>
    <% end %>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
  <p><%= form.label :body, 'Text question' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>
  <p class="mt"><%= form.label :user_id %></p>
  <p><%= form.text_field :user_id, class: 'form-text-field'%></p>
  <p class="mt"><%= form.submit 'Save', class: 'button button-main'%></p>
<% end  %>

app/views/questions/_question.html.erb
<div class="mb-sm">
  <%= question.body %>
</div>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short)%>
  </div>

  <div>
    <%= link_to fa_icon('pencil'), edit_question_path(@question), title: 'Edit question' %>
    <%= button_to fa_icon('trash-o'), question_path(@question), method: :delete, title: 'Delete question' %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Edit question <%= @question.id %></h2>
  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb"> Questions </h2>

  <% @questions.each do |question| %>
    <p class="mb-sm"><%= link_to "Question #{question.id}", question_path(question)%></p>
  <% end %>

  <p class ='mt'> Create questions</p>

  <p class="mt">
    <%= render 'form', question: @question %>
  </p>
</div>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb" > New question</h2>
  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb"> Question <%= @question.id %></h2>

  <%= render 'question', question: @question %>
  <p class ='mt'><%= link_to 'All questions', questions_path %></p>
</div>